/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface DeckgoGamepad {}
  interface DeckgoGamepadAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DeckgoGamepad': Components.DeckgoGamepad;
  }

  interface StencilIntrinsicElements {
    'deckgo-gamepad': Components.DeckgoGamepadAttributes;
  }


  interface HTMLDeckgoGamepadElement extends Components.DeckgoGamepad, HTMLStencilElement {}
  var HTMLDeckgoGamepadElement: {
    prototype: HTMLDeckgoGamepadElement;
    new (): HTMLDeckgoGamepadElement;
  };

  interface HTMLElementTagNameMap {
    'deckgo-gamepad': HTMLDeckgoGamepadElement
  }

  interface ElementTagNameMap {
    'deckgo-gamepad': HTMLDeckgoGamepadElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
